# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: antsmallant
email: 412288482@qq.com
name: antsmallant
description: >- # this means to ignore newlines until "baseurl:"
  提问，总结，书写
keywords: [c++ c golang lua database]
baseurl:
url: 'https://blog.antsmallant.top' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'blog.antsmallant.top' # the domain name for your site, e.g. example.com
author: 'antsmallant'
language: zh-cn
# Supported languages list:
# en: English
# de: Deutsche (German)
# es: Español (Spanish)
# fr: Français (French)
# ja: 日本語 (Japanese)
# pt: Português (Portuguese)
# zh-cn: 简体中文 (Simplified Chinese)
# zh-tw: 繁體中文 (Traditional Chinese)
# ko : 한국어 (Korean)

analytics: G-6V79Y60CKY # the Google Analytics property ID, e.g. UA-XXXXX-Y

comments: true  # enable comments
comments_provider: giscus # choose one comment provider
disqus: antsmallant # disqus account
giscus:
    repo: antsmallant/antsmallant.github.io
    repo-id: R_kgDOJzINng
    category: Announcements
    category-id: DIC_kwDOJzINns4CZsEQ

mathjax: true # Math support
diagram: true # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded # compressed, compact, expanded or compressed

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

remote_theme: benbalter/retlab